config/routes.rb
Auth::Application.routes.draw do
  root :to => "home#index" #The home page
  resource :index

  get "scriptresult" => "home#scriptresult"

  get "signed_out" => "authentication#signed_out" #logout
  get "sign_in" => "authentication#sign_in"
  post "sign_in" => "authentication#login"
  get "new_user" => "authentication#new_user"
  post "new_user" => "authentication#register"
  get "admin_users" => "admin#users"
  delete 'user/:id' => "admin#delete_user", as: :user #Gets the ID of the user and delete it from the 

end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base
	def initialize(attributes = {})
    super # must allow the active record to initialize!
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end
end

app/models/node.rb
class Node < ActiveRecord::Base
	def initialize(attributes = {})
    super # must allow the active record to initialize!
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end
end

app/models/testbed.rb
class Testbed < ActiveRecord::Base
	def initialize(attributes = {})
    super # must allow the active record to initialize!
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :remember_me, :email, :username, :password, :password_confirmation
  attr_accessor :remember_me, :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email, :on => :create
  validates_presence_of :username, :on => :create
  validates_uniqueness_of :email
  validates_uniqueness_of :username

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.encrypted_password == BCrypt::Engine.hash_secret(password, user.salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.encrypted_password = BCrypt::Engine.hash_secret(password, salt)
    end
  end

  def self.authenticate_by_email(email, password)
    user = find_by_email(email)
    if user && user.encrypted_password == BCrypt::Engine.hash_secret(password, user.salt)
      user
    else
      nil
    end
  end

  def self.authenticate_by_username(username, password)
    user = find_by_username(username)
    if user && user.encrypted_password == BCrypt::Engine.hash_secret(password, user.salt)
      user
    else
      nil
    end
  end
  
  def initialize(attributes = {})
    super # must allow the active record to initialize!
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def users
    if !current_user
      redirect_to :root
    end 
    @users = User.all
  end

  def delete_user
    if params[:id] == current_user.id.to_s
      flash.now[:error] = 'You cannot delete yourself!'
      @users = User.all
      render :action => :users
    else
      User.find_by_id(params[:id]).delete
      @users = User.all
      render :action => :users
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    #Note: we want to use "find_by_id" because it's OK to return a nil
    #if we were to use User.find, it would throw an exception if the user can't be found
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end

end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  before_filter :authenticate_user, :only => [:account_settings, :set_account_info]

def sign_in
  @user = User.new
end
#For signing in
def login
  username_or_email = params[:user][:username]
  password = params[:user][:password]

  if username_or_email.rindex('@')
    email = username_or_email
    user = User.authenticate_by_email(email, password)
  else
    username = username_or_email
    user = User.authenticate_by_username(username, password)
  end

  if user
    user.last_signed_in_on = DateTime.now
    user.save
    session[:user_id] = user.id
    flash[:notice] = 'Welcome'
    redirect_to :root
  else
    flash[:error] = 'Unknown user. Please check your username and password.'
    render :action => "sign_in"
  end

end
#Signing out
def signed_out
  session[:user_id] = nil
  flash[:notice] = 'You have been signed out.'
end
#To register a new user
def new_user
    @user = User.new
end

def register
    @user = User.new(params[:user])

    if @user.valid?
      @user.signed_up_on = DateTime.now
      @user.last_signed_in_on = @user.signed_up_on
      @user.save
      session[:user_id] = @user.id
      flash[:notice] = 'Welcome.'
      redirect_to :root
    else
      render :action => "new_user"
    end
end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if !current_user
  		redirect_to sign_in_path
  	end
  	@nodes = Node.all
  	@neighs = Neighborhood.all
  end

  def scriptresult
  	if !current_user
  		redirect_to sign_in_path
  	end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def show_field_error(model, field)
    s=""

    if !model.errors[field].empty?
      s =
          <<-EOHTML
            <div_id="error_message">
              #{model.errors[field][0]}
            </div>
          EOHTML
    end

    s.html_safe
  end

end

app/helpers/layout_helper.rb
module LayoutHelper

  def bootstrap_version
    # Choose the Bootstrap version you would like to use from the CDN
    "3.1.1"
  end

end

app/views/admin/users.html.erb
<p>Admin Users</p>
<table>
  <tr>
    <th width="20%">E-mail</th>
    <th width="20%">Username</th>
    <th width="20%">Signed Up On</th>
    <th width="20%">Last Signed In On</th>
  </tr>
  <% for user in @users %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.username %></td>
      <td><%= user.signed_up_on %></td>
      <td><%= user.last_signed_in_on %></td>
      <td><%= link_to 'Delete', user, :confirm => 'Are you sure?Really?!', :method => :delete %></td>
    </tr>
  <% end %>
</table>

app/views/authentication/new_user.html.erb
<div class="text-center">
<p>Sign up</p>
<%= form_for @user, :as => :user, :url => new_user_path do |f| %>
<p>
  <%= f.label 'username:' %><br />
  <%= f.text_field :username %>
  <%= show_field_error(@user, :username) %>
</p>
<p>
  <%= f.label 'email:' %><br />
  <%= f.text_field :email %>
  <%= show_field_error(@user, :email) %>
</p>
<p>
  <%= f.label 'password:' %><br />
  <%= f.password_field :password %>
  <%= show_field_error(@user, :password) %>
</p>
<p>
  <%= f.label 'password confirmation:' %><br />
  <%= f.password_field :password_confirmation %>
  <%= show_field_error(@user, :password_confirmation) %>
</p>
<p>
  <%= f.submit 'Sign Up', :class => 'form_control btn btn-primary' %>&nbsp;&nbsp;&nbsp;
  <%= f.submit 'Clear Form', :type => 'reset' , :class => 'form_control btn btn-primary' %>
</p>
<% end %>
<div>

app/views/authentication/sign_in.html.erb
<div class="text-center">
<p>Sign In</p>
<%= form_for @user, :as => :user, :url => sign_in_path do |f| %>
    <p>
      <%= f.label 'username or email:' %><br />
      <%= f.text_field :username %>
      <%= show_field_error(@user, :username) %>
    </p>
    <p>
      <%= f.label 'password:' %><br />
      <%= f.password_field :password %>
      <%= show_field_error(@user, :password) %>
    </p>
    <p>
      <%= f.submit 'Sign In', :class => 'form_control btn btn-primary' %>&nbsp;&nbsp;&nbsp;
      <%= f.submit 'Clear Form', :type => 'reset', :class => 'form_control btn btn-primary' %>
    </p>
<% end %>
</div>

app/views/home/index.html.erb
<meta charset="utf-8">
<style>
.draggable { z-index: 1; float: left; background: transparent; border: none; position: relative; cursor: progress; width: 100%; }
  #sideBar { vertical-align:top;}
  #contentArea { vertical-align:top;}
  #rightSideBar { vertical-align:top;}
b { 
   position: absolute; 
   top: 15px; 
   left: 3px; 
   width: 100%; 
}
</style>
<script type="text/javascript">
  var testbed_neighborhoods = {};
  var testbed_ips = {};
  <% for list in @neighs %>
  testbed_neighborhoods[<%= list.node_id.to_json %>] = "";
  <% end %>
  <% for list in @neighs %>
  testbed_neighborhoods[<%= list.node_id.to_json %>] += <%= list.neighborhoods.to_json %> + " ";
  <% end %>
  <% for list in @nodes %>
  testbed_ips[<%= list.id.to_json %>] = "<%= list.control_ip %>";
  <% end %>
</script>
    <div id="myModal" class="modal fade in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Script gerado</h4>
      </div>
      <pre id="texto" class="modal-body">
# Definição do grupo server
defGroup('server', "<span id="nodename1">omf.ufg.node1</span>") do |node|
    node.net.e1.ip = "<span id="ip1">192.168.10.1</span>"

    # Adiciona uma aplicação pré-definida
    node.addApplication("oml:app:iperf") do |app|
        # Configura propriedades pré-definidas na aplicação
        app.setProperty('server', true)
        app.setProperty('port', 5000)
    end
end

# Definição do grupo client
defGroup('client', "<span id="nodename2">omf.ufg.node2</span>") do |node|
    node.net.e1.ip = "<span id="ip2">192.168.10.2</span>"
    # Adiciona uma aplicação pré-definida
    node.addApplication("oml:app:iperf") do |app|
        # Configura propriedades pré-definidas na aplicação
        app.setProperty('client', '<span id="ip3">192.168.10.1</span>')
        app.setProperty('port', 5000)
        app.setProperty('time', 30)
        app.setProperty('interval', '1')
        
        # Define qual ponto de medida será coletado e como será feito a coleta
        app.measure('transfer', :samples => 1)
    end
end

#A execução do experimento é condicionada ao evento ALL_UP_AND_INSTALLED, isto é, o experimento só terá inicio quando todos os nós tiverem ligados e com as aplicações definidas acima devidamente instaladas. 
onEvent(:ALL_UP_AND_INSTALLED) do |event|
    wait 5
  #Inicia a aplicação definida no grupo server
    group("server").startApplications
    wait 5
  #Inicia a aplicação definida no grupo client
    group("client").startApplications
    wait 40
    #Pausa execução das aplicações em todos os grupos
    allGroups.stopApplications
    #Faz a chamada para finalizar o experimento
    Experiment.done
end
      </pre>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <button type="button" class="btn btn-primary" value="Download" id="downs">Download</button>
      </div>
  </div>
<div><b> Menu de movimentacao das testbeds!</b><br />LabWiki v1.0</div>
<table>
 <tr>
  <td id="sideBar">
    <% for list in @nodes %>
    <ul>
      <div align="left" id=<%= list.id %> class="draggable ui-widget-content arrastavel">
      <a href="#"><img src="/testbed2.png" ></a>
      <b>Node<%= list.id %></b>  
    </div>
    </ul>
    <% end %>
  </td>

  <td id="contentArea">
    <div align="center" id="containment-wrapper" class="index">
      <div id="container"><canvas id="imageTemp" height="500" width="500"></canvas>
      <!--<canvas id="imageTemp" width="500" height="250"></canvas>--></div>
    </div>
  </td>

  <td id="rightSideBar">
    <div id="testbed_name">Clique em um dos nós!</div>
    <div id="testbed_ip">IP do nó...</div>
    <div id="testbed_con">Testbed conectada com...</div>

    <br><div id="testbed_name2">Clique em um dos nós!</div>
    <div id="testbed_ip2">IP do nó...</div>
    <div id="testbed_con2">Testbed conectada com...</div></br>
    <input type="button" class="btn btn-default" value="Congelar" id="freeze">
    <input type="button" class="btn btn-warning" value="Resetar" id="reset">
    <input type="button" class="btn btn-success" href="#myModal" data-toggle="modal" value="Gerar Script" id="script"> 
  </td>
</tr>
</table>

app/views/home/scriptresult.html.erb
<script type="text/javascript">
  var mello = "trello";
</script>
<div id="texto">
  # Definição do grupo server
  defGroup('server', "<div id="nodename1">omf.ufg.node1</div>") do |node|
      node.net.e1.ip = "<div id="ip1">192.168.10.1</div>"

      # Adiciona uma aplicação pré-definida
      node.addApplication("oml:app:iperf") do |app|
          # Configura propriedades pré-definidas na aplicação
          app.setProperty('server', true)
          app.setProperty('port', 5000)
      end
  end

  # Definição do grupo client
  defGroup('client', "<div id="nodename2">omf.ufg.node2</div>") do |node|
      node.net.e1.ip = "<div id="ip2">192.168.10.2</div>"
      # Adiciona uma aplicação pré-definida
      node.addApplication("oml:app:iperf") do |app|
          # Configura propriedades pré-definidas na aplicação
          app.setProperty('client', '<div id="ip3">192.168.10.1</div>')
          app.setProperty('port', 5000)
          app.setProperty('time', 30)
          app.setProperty('interval', '1')
          
          # Define qual ponto de medida será coletado e como será feito a coleta
          app.measure('transfer', :samples => 1)
      end
  end

  #A execução do experimento é condicionada ao evento ALL_UP_AND_INSTALLED, isto é, o experimento só terá inicio quando todos os nós tiverem ligados e com as aplicações definidas acima devidamente instaladas. 
  onEvent(:ALL_UP_AND_INSTALLED) do |event|
      wait 5
    #Inicia a aplicação definida no grupo server
      group("server").startApplications
      wait 5
    #Inicia a aplicação definida no grupo client
      group("client").startApplications
      wait 40
      #Pausa execução das aplicações em todos os grupos
      allGroups.stopApplications
      #Faz a chamada para finalizar o experimento
      Experiment.done
  end
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Auth</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css"> 
  <script src="//code.jquery.com/jquery-1.9.1.js"></script> 
  <script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script> 
  <%= javascript_include_tag "http://netdna.bootstrapcdn.com/bootstrap/"+bootstrap_version+"/js/bootstrap.min.js" %>
  <%= stylesheet_link_tag "http://netdna.bootstrapcdn.com/bootstrap/"+bootstrap_version+"/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "scripts" %>
  <%= javascript_include_tag "FileSaver" %>
  <%= csrf_meta_tags %>
</head>
<body>
<p>
  <% if current_user %>
      Logged in as <%= current_user.username %>
      <%= link_to "Sign out", signed_out_path %>
      <%= link_to "Admin", admin_users_path %>
      <%= link_to "Home", :root %>
  <% else %>
      <%= link_to "Sign up", new_user_path %> or
      <%= link_to "Sign in", sign_in_path %>
  <% end %>
</p>

<% flash.each do |name, msg| %>
<%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
<%= yield %>
</body>
</html>